<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>BDOLootTracker.App</StartupObject>
    <Version>0.10.4</Version>
    <AssemblyVersion>0.10.4.0</AssemblyVersion>
    <FileVersion>0.10.4.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.*" />
    <PackageReference Include="PacketDotNet" Version="1.*" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.*" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.*" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>
</Project>
