using System.Diagnostics;
using System.Reflection;
using System.Text.Json;
using BDOLootTracker.Models;

namespace BDOLootTracker.Services;

public sealed class ParserCalibrationSubmissionService
{
    private const string NewIssueUrl =
        "https://github.com/Shoki697/BDOLootTracker/issues/new";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = false,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public static string CurrentAppVersion
    {
        get
        {
            Version? version = Assembly.GetEntryAssembly()?.GetName().Version;
            if (version == null)
                return "0.12.7";

            return $"{version.Major}.{version.Minor}.{version.Build}";
        }
    }

    public void OpenGitHubSubmission(ParserCalibrationReport report)
    {
        string json = JsonSerializer.Serialize(report, JsonOptions);
        string title = $"[Parser Calibration] {report.BaseOfficialVersion} -> community candidate";
        string body =
            "This issue was generated by BDO Loot Tracker Manual Calibration.\n\n" +
            "The repository workflow will validate the report and, if valid, publish it as a community parser candidate. " +
            "No account, character, IP address, loot history or packet capture is included.\n\n" +
            "<!-- BDO_PARSER_REPORT_BEGIN -->\n" +
            "```json\n" + json + "\n```\n" +
            "<!-- BDO_PARSER_REPORT_END -->";

        string url = NewIssueUrl +
                     "?title=" + Uri.EscapeDataString(title) +
                     "&body=" + Uri.EscapeDataString(body);

        Process.Start(new ProcessStartInfo
        {
            FileName = url,
            UseShellExecute = true
        });
    }
}
